apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: jttours
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://$(oc get svc mysql-service -n jttours -o jsonpath='{.spec.clusterIP}')/jttoursdb
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admin"