apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: jttours
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://172.21.171.36/jttoursdb"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admin"