apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: jttours
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/mysql/data"
 
---
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: jttours
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi